CREATE TABLE IF NOT EXISTS medicamentos
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome               VARCHAR(255),
    principio_ativo    VARCHAR(255),
    quantidade_estoque INTEGER                                 NOT NULL,
    dosagem            DOUBLE PRECISION                        NOT NULL,
    observacoes        VARCHAR(255),
    usuario_id         BIGINT,
    frequencia_uso_id  BIGINT,
    CONSTRAINT pk_medicamentos PRIMARY KEY (id)
);

ALTER TABLE medicamentos
    ADD CONSTRAINT uc_medicamentos_frequencia_uso UNIQUE (frequencia_uso_id);

ALTER TABLE medicamentos
    ADD CONSTRAINT FK_MEDICAMENTOS_ON_FREQUENCIA_USO FOREIGN KEY (frequencia_uso_id) REFERENCES frequencia_uso (id);

ALTER TABLE medicamentos
    ADD CONSTRAINT FK_MEDICAMENTOS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);